### ISSUE TITLE
Improve join button

### ISSUE THREAD

**Issue by RyanT5** [freshairradio/website#4]
The join button could be more in line with the aesthetic of the rest of the site.

<img width="127" alt="Screenshot 2020-10-27 at 12 39 21" src="https://user-images.githubusercontent.com/22382958/97336299-c2e61c00-1876-11eb-8960-1eb3bc8563fd.png">

**Comment by penalosa** [comment]
For some more details: this probably involved lowercasing the font, bumping the font size a touch, increasing the padding, and vertically centering the text in the button

**Comment by malavivenkatesh** [comment]
How about this? Is the font too thin?
![image](https://user-images.githubusercontent.com/15332973/97786149-8f223380-1ba1-11eb-931c-a5fe87891289.png)

**Comment by RyanT5** [comment]
That text looks much better!

How about some padding on the sides and maybe even add an icon like the menu? You could also play about with a transulcent background and white text that goes opaque on hover or something and see how it looks?

**Comment by malavivenkatesh** [comment]
I've done a transition and translucent background now which is pushed. I think it fits better

**Comment by penalosa** [comment]
Very nice!
